repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.3"
    hooks:
      - id: ruff-format
  - repo: https://github.com/PyCQA/isort
    rev: "5.13.2"
    hooks:
      - id: isort
  - repo: local
    hooks:
      # shoutout to https://github.com/RobertCraigie/pyright-python
      - id: pyright
        name: pyright
        description: "Python command line wrapper for pyright, a static type checker"
        entry: basedpyright
        language: python
        "types_or": [python]
        require_serial: true
        additional_dependencies:
          - basedpyright>=1.25.0
          - pydantic>=2.10.6
          - pyyaml>=6.0.2
          - typer>=0.12.5
        minimum_pre_commit_version: "2.9.2"
